server {
    listen 80;
    server_name _;

    # ИСПРАВЛЕННЫЙ БЛОК ДЛЯ S3 PROXY
    location /s3-proxy/ {
        # Используем DNS Cloud.ru или Google для обновления IP
        resolver 8.8.8.8 valid=30s;
        
        # Разрешаем методы, необходимые браузеру
        proxy_method GET; # ЖЕСТКО форсируем метод GET, чтобы исключить ошибку 405
        
        proxy_hide_header 'Access-Control-Allow-Origin';
        proxy_hide_header 'Access-Control-Allow-Methods';
        proxy_hide_header 'Access-Control-Allow-Headers';
        
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;

        if ($request_method = 'OPTIONS') {
            return 204;
        }

        # Перенаправляем запрос. Nginx автоматически заменит "/s3-proxy/" на "/"
        # То есть "/s3-proxy/news/NEW.txt" превратится в "/news/NEW.txt"
        proxy_pass https://cloud.ru; 
        
        proxy_set_header Host racehub.s3.cloud.ru;
        proxy_set_header X-Real-IP $remote_addr;
        
        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
        proxy_buffering off;
    }


    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://webapp:80/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
