server {
    listen 80;
    server_name _;

    # ИСПРАВЛЕННЫЙ БЛОК ДЛЯ S3 PROXY
        location /s3-proxy/ {
        resolver 8.8.8.8 valid=30s;
        
        # 1. Сбрасываем заголовки, из-за которых Cloud.ru ругается ошибкой 405
        proxy_set_header Origin "";
        proxy_set_header Referer "";
        
        # 2. Жестко переопределяем Host на имя бакета
        proxy_set_header Host racehub.s3.cloud.ru;
        
        # 3. Настраиваем правильное проксирование путей
        proxy_pass https://cloud.ru;
        
        # 4. Стираем оригинальные CORS заголовки S3 (если они кривые)
        proxy_hide_header 'Access-Control-Allow-Origin';
        proxy_hide_header 'Access-Control-Allow-Methods';
        proxy_hide_header 'Access-Control-Allow-Headers';
        
        # 5. Выдаем вашему Vue-сайту идеальные права доступа
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;

        # Быстрый ответ для preflight-запросов браузера
        if ($request_method = 'OPTIONS') {
            return 204;
        }

        # Опции стабильности SSL соединения
        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
        proxy_buffering off;
    }




    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://webapp:80/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
